### PR TITLE
Fix getArgument() notice.

### PR DESCRIPTION
**Pull request by sepehr**
The PR fixes the `Shipper::getArgument()` alongside with few other very minor issues.

### CODE REVIEW

**Comment by AndrewFeeney** [comment]
👍

**Comment by sepehr** [comment]
The notice won't be gone unless we tag a release.

**Comment by AndrewFeeney** [comment]
Tagged 1.1.2

**Comment by sepehr** [comment]
Still getting the error as it's not yet reflected on [packagist](https://packagist.org/packages/makeweb/shipper). Do we have the packagist service hook set up for this repo?

**Comment by AndrewFeeney** [comment]
The hook is set up but a conflict between the version in the `composer.json` and the tagged version was preventing the automatic update. I removed the version from composer.json to prevent this issue in future.

**Pull request merged**
